<?php // Generated by AbstractFormat of file 'config.base.yml'
return array (
  'controller' => 
  array (
    'instances' => 
    array (
      'test' => 
      array (
        'name' => 'test',
      ),
      'test2' => 
      array (
        'name' => 'test2',
      ),
    ),
  ),
  'DEVMODE' => true,
  'TEST' => true,
  'bootstrap' => 
  array (
    'database' => 
    array (
      'file' => 'includes/data/source/db/DBConnection.php',
      'config' => 'databases',
    ),
    'errorhandler' => 
    array (
      'file' => 'includes/error/ErrorHandler.php',
      'priority' => true,
    ),
    'logger' => 
    array (
      'file' => 'includes/logger/Logger.php',
      'config' => 'logger',
      'priority' => true,
    ),
  ),
  'databases' => 
  array (
    'mainmysql' => 
    array (
      'driver' => 'mysql',
      'host' => '127.0.0.1',
      'port' => '3306',
      'password' => '',
      'user' => 'root',
      'database' => 'test',
      'alias' => 'main',
    ),
  ),
  'logger' => 
  array (
    'target' => 'file',
    'level' => 'debug',
    'file' => '/opt/lampp/htdocs/work/project/log/application.log',
  ),
);